country: china

users:
  name: tom
  age: 18

likes:
  - music
  - sports
  - travel


baseDir: c:\win10

tempDir: ${baseDir}\temp
server:
  port: 80


datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/db02
  username: root
  password: qwer1234
